### ISSUE TITLE
Please use a more permissive license

### ISSUE THREAD

**Issue by Fuuzetsu** [NorfairKing/easyspec#2]
Hi,

I wanted to contribute/fork the project (in fact already did) but I just noticed the whole code is under All rights reserved technically meaning noone can use it or modify it.

Please consider a different license such that forks or contributions are possible or alternatively please state terms of use, modifications and contributions in README.

Thanks!

**Comment by NorfairKing** [comment]
Working on it, I essentially just have to choose one. Will discuss it and get back to you.
